### ISSUE TITLE
Collision with generated slugs

### ISSUE THREAD

**Issue by jmarchewka** [nyuhsl/data-catalog#136]
Storing entities with similar titles (ie, citations) will fail with an SQL collision error on the slug.

**Comment by jmarchewka** [comment]
We will need to either make the slugs editable (with an insertion/update fail on a collision) or generate a unique slug.

**Comment by ianlamb77** [comment]
Thanks for reporting. I'd be fine with either of those options, leaning towards making a unique slug. My understanding though is that typically we don't actually want to allow duplicates of these entities. Are you seeing two different citations that are generating the same slug? That could point to another issue.

**Comment by jmarchewka** [comment]
The entity that spawned this problem was unique, but similar to another entity within the slug generation space (first 100 characters.)

Is it important that the slugs be completely human readable? Would generating a hex hash of the title and appending it to the end be acceptable? I would keep the dataset slugs the same as they are now.

**Comment by ianlamb77** [comment]
Ah OK, that makes sense. No, it's not important that they be entirely human-readable, so the hex hash idea is great.

**Comment by ianlamb77** [comment]
hey Joel I was gonna go ahead and start working on this, unless you were already doing so.

**Comment by ianlamb77** [comment]
#136 should address this, though it reminded me why I used the slug field to enforce uniqueness on this entity in the first place -- the 'citation' field is too long to be indexed in older versions of MySQL. 

With the current pull request, any existing citation could be added again since the new one will have a hash at the end of the slug. This is probably not that big of a deal for many institutions but it's something to be mindful of. Any thoughts?

**Comment by jmarchewka** [comment]
Ian,

That’s fine, I won’t be able to get back onto DC work for another week or so.
