### ISSUE TITLE
"Website User"

### ISSUE THREAD

**Issue by bohyunkim** [nyuhsl/data-catalog#19]
What is the purpose of "Website user"? It looks like I can create them but it doesn’t appear to play a role for any type of authentication. Also the "Add User" form for this has the "Website Role" field that doesn’t have any input option for it. Is that intentional?

**Comment by ianlamb77** [comment]
Hello, the idea of the website user is that individuals are granted administrative access to this website using that form, and would log in either through your institution's SSO/AD system or via Symfony's built-in user authentication. However that authentication piece is not implemented in this repository, since it will likely be different for every institution. That's why, as you noticed, the users you create here have no effect yet. The only default user is the "admin" user contained in security.yml.example.

The website roles would correspond to different levels of privileges that you want users to have. With #21 I've added another default user to security.yml.example, a non-administrative account so you can see what the interface looks like to them. Basically, they are only able to add a new dataset, and they are given a much shorter data entry form. The idea is that a researcher could log in and add their own datasets which would be reviewed by the site admins. The "roles" field in the form is blank because the choices are taken from the database, which I will be adding to the documentation. For example our datacatalog_user_roles table looks like this:

![image](https://cloud.githubusercontent.com/assets/5383580/25955714/f8968f12-3637-11e7-9458-7a97b75c8442.png)

**Comment by bohyunkim** [comment]
Thanks!
