### ISSUE TITLE
Solr v5 or v6 support

### ISSUE THREAD

**Issue by zburke** [nyuhsl/data-catalog#9]
Based on the Solr config files mentioned in the README, and some java errors when I tried copying the provided `SolrSchemaSample.xml` file into my Solr config, it looks like this project is using Solr v4.x. As noted on the [Solr community support page](http://lucene.apache.org/solr/community.html) everything less than 5.5 is unsupported. Has anybody gotten it running against a newer Solr installation?

**Comment by ianlamb77** [comment]
The incompatibility was just discovered recently by another institution and I'm still looking into what would be necessary to support the newer versions. The biggest issue I see is that newer versions do not use these configuration files -- you feed them documents and they try to "guess" the schema. This requires the user to enter some datasets (or perhaps some "dummy" datasets) that can be indexed by Solr, before any searching can be done. I think it should be fairly simple to allow this, but I'm not sure yet how well that "guessing" works, or how the facets are handled.

**Comment by ianlamb77** [comment]
With #20  I've included a new custom schema and made some other changes that should make us compatible with v6. The new custom schema is based on the "managed-schema" automatically generated by v6, which seems to work fine but I haven't tested it extensively so I can't vouch for the nitty-gritty of how well it searches. I would imagine they did a good job though since they are the experts.

There are a couple minor changes to the solrconfig.xml file which have to be made to support the custom schema, there are links to documentation in the readme. Also one change in the parameters.yml.example which needs to be applied to your local copy. 

The Solr Indexer scripts should still work with v6. I haven't run through the entire install process using v6 so there might be some hiccups, but as long as Solr is set up with the custom schema before trying to log into the data catalog I think it should work.
